server:
  port: 8001
spring:
  data:
    mongodb:
      host: 192.168.171.128
      database: ZuiBlog
      port: 27017
      username: dazuizui
      password: admin
  application:
    name: app-user
  rabbitmq:
    host: 192.168.171.128
    port: 5672
    username: dazui
    password: admin
    virtual-host: /             #虚拟主机地址
  cloud:
    stream:
      bindings:
        # 博文添加
        blog_add_input:
          destination: blog_exchange_add
        blog_add_output:
          destination: blog_exchange_add
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # set @@GLOBAL.sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
    url: jdbc:mysql://127.0.0.1:3306/zuioj
    username: root
    password: admin
  redis:
    # Redis Url
    host: 127.0.0.1
    # Redis 端口
    port: 6379
    # Redis 密码
    # password: 您的密码
    # 设置数据库序号
    database: 0

  servlet:
    #文件上传
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 500MB #最大请求文件的大小
      max-file-size: 500MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入

# 选择api项目下的resouces路径下的user文件夹
filePath: "/Users/yangyida/Documents/project/ZuiOJ/ZuiOJ/basic-api/src/main/resources/users/"
# 服务器url路径
projecturl: "http://127.0.0.1:8001"