server:
  port: 8001
spring:
  data:
    mongodb:
#      host: 192.168.171.128
      host: 192.168.0.211
#      database: ZuiBlog
      database: gsoj
      port: 27017
#      username: dazuizui
      username: gsoj
#      password: admin
      password: xiangjiaochuanmei
  application:
    name: app-user
  rabbitmq:
#    host: 192.168.171.128
    host: 192.168.0.211
    port: 5672
#    username: dazui
#    password: admin
    username: dazui
    password: xiangjiaochuanmei
    virtual-host: /             #虚拟主机地址
  cloud:
    stream:
      bindings:
        #比赛时提交代码
        contest_code_add_input:
          destination: contest_code_exchange_add
        contest_code_add_output:
          destination: contest_code_exchange_add
        # 博文添加
        blog_add_input:
          destination: blog_exchange_add
        blog_add_output:
          destination: blog_exchange_add
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # set @@GLOBAL.sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
#    url: jdbc:mysql://127.0.0.1:3306/zuioj
    url: jdbc:mysql://192.168.0.211:3306/guangshaoj
#    username: root
#    password: admin
    username: yangyida
    password: wasd123..wasd
  redis:
    # Redis Url
    host: 192.168.0.211
    # Redis 端口
    port: 6379
    # Redis 密码
    # password: 您的密码
    password: xiangjiaochuanmei
    # 设置数据库序号
    database: 0

  servlet:
    #文件上传
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 500MB #最大请求文件的大小
      max-file-size: 500MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入

# 选择api项目下的resouces路径下的user文件夹
filePath: "/Users/yangyida/Documents/project/ZuiOJ/ZuiOJ/basic-api/src/main/resources/users/"
# 服务器url路径
projecturl: "http://192.168.0.211:8001"